### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by bdapp** [gpt-3-5-turbo-web/gpt-3-5-turbo-web-docker#1]
请问输入账号密码登录提示“SyntaxError: Unexpected end of JSON input”怎么解？

**Comment by SadPencil** [comment]
这说明后端没有启动成功。访问 http://域名:端口/backend/ 后应当出现 django 后端的界面

**Comment by bdapp** [comment]
> 这说明后端没有启动成功。访问 [http://域名:端口/backend/](http://%E5%9F%9F%E5%90%8D:%E7%AB%AF%E5%8F%A3/backend/) 后应当出现 django 后端的界面

是的，backend的镜像exited了，感谢！

**Comment by bdapp** [comment]
> > 这说明后端没有启动成功。访问 [http://域名:端口/backend/](http://%E5%9F%9F%E5%90%8D:%E7%AB%AF%E5%8F%A3/backend/) 后应当出现 django 后端的界面
> 
> 应该是启动成功了，访问backend链接是能看到登录框的

**Comment by SadPencil** [comment]
backend镜像应该不会自己exit。你可以试试重新git clone一下最新的 [gpt-3-5-turbo-web-docker](https://github.com/gpt-3-5-turbo-web/gpt-3-5-turbo-web-docker) 代码，重新部署一次。
